/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import java.awt.Color;
import Koneksi.Db_Koneksi;
import com.mysql.jdbc.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author NURANISDA
 */
public class cari_buku extends javax.swing.JFrame {
  private DefaultTableModel model;
            int mouseX,mouseY;
     String np,id_buku,id_anggota,jumlah;
 
      public void getDataBuku(){
       model.getDataVector();
       model.fireTableDataChanged();
      
       this.setLocationRelativeTo(null);
       try{
           com.mysql.jdbc.Statement stat = (com.mysql.jdbc.Statement) Db_Koneksi.getKoneksi().createStatement();
           String sql = "select * from databuku";
           ResultSet res = stat.executeQuery(sql);
           while(res.next()){
               Object[] obj = new Object[5];
               obj[0]=res.getString("id_buku");
               obj[1]=res.getString("judul_buku");
               obj[2]=res.getString("penerbit");
               obj[3]=res.getString("pengarang");
               obj[4]=res.getString("stok");
               model.addRow(obj);
           }
       }catch(SQLException err){
           
       }
   }
       

    /**
     * Creates new form cari_buku
     */
    public cari_buku() {
        initComponents();
             model = new DefaultTableModel();
       jTable1.setModel(model);
        model.addColumn("id_buku");
        model.addColumn("judul_buku");
        model.addColumn("penerbit");
        model.addColumn("pengarang");
        model.addColumn("stok");
        
        getDataBuku();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_exit1 = new javax.swing.JButton();
        jButton_minimize1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField_searchbook = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField_idbuku = new javax.swing.JTextField();
        jTextField_judul = new javax.swing.JTextField();
        jTextField_pengarang = new javax.swing.JTextField();
        jTextField_penerbit = new javax.swing.JTextField();
        jTextField_stok = new javax.swing.JTextField();
        jLabel_stok = new javax.swing.JLabel();
        jLabel_penerbit = new javax.swing.JLabel();
        jLabel_pengarang = new javax.swing.JLabel();
        jLabel_judul = new javax.swing.JLabel();
        jLabel_idbuku = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(153, 102, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/foto/icons8_administrator_52px_1.png"))); // NOI18N
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 60));

        jLabel18.setBackground(new java.awt.Color(139, 71, 38));
        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Hello, Admin!");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 160, 35));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 930, 140));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 660, 280));

        jButton_exit1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_exit1.setForeground(new java.awt.Color(255, 0, 0));
        jButton_exit1.setText("x");
        jButton_exit1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_exit1MouseClicked(evt);
            }
        });
        jButton_exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exit1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton_exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 30, -1));

        jButton_minimize1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_minimize1.setForeground(new java.awt.Color(255, 0, 0));
        jButton_minimize1.setText("-");
        jButton_minimize1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_minimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_minimize1MouseClicked(evt);
            }
        });
        jButton_minimize1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_minimize1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton_minimize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 30, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField_searchbook.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_searchbook.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_searchbook.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_searchbook.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_searchbookFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_searchbookFocusLost(evt);
            }
        });
        jTextField_searchbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_searchbookActionPerformed(evt);
            }
        });
        jTextField_searchbook.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_searchbookKeyReleased(evt);
            }
        });
        jPanel1.add(jTextField_searchbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 13, 260, 30));

        jButton1.setText("search");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 13, -1, -1));

        jTextField_idbuku.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_idbuku.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_idbukuFocusGained(evt);
            }
        });
        jTextField_idbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idbukuActionPerformed(evt);
            }
        });
        jTextField_idbuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_idbukuKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_idbukuKeyTyped(evt);
            }
        });
        jPanel1.add(jTextField_idbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 260, 30));

        jTextField_judul.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_judul.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_judulFocusGained(evt);
            }
        });
        jTextField_judul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_judulActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 260, 30));

        jTextField_pengarang.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_pengarang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_pengarangFocusGained(evt);
            }
        });
        jTextField_pengarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_pengarangActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_pengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 260, 30));

        jTextField_penerbit.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_penerbit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_penerbitFocusGained(evt);
            }
        });
        jTextField_penerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_penerbitActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_penerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 260, 30));

        jTextField_stok.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_stok.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_stokFocusGained(evt);
            }
        });
        jTextField_stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_stokActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 260, 30));

        jLabel_stok.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabel_stok.setText("Stok:");
        jPanel1.add(jLabel_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jLabel_penerbit.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabel_penerbit.setText("Penerbit:");
        jPanel1.add(jLabel_penerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel_pengarang.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabel_pengarang.setText("Pengarang:");
        jPanel1.add(jLabel_pengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel_judul.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabel_judul.setText("Judul Buku:");
        jPanel1.add(jLabel_judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel_idbuku.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabel_idbuku.setText("Id Buku:");
        jPanel1.add(jLabel_idbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 930, 230));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/foto/large3.jpg"))); // NOI18N
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 700));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 0, 1090, -1));

        jPanel2.setBackground(new java.awt.Color(255, 215, 0));
        jPanel2.setMaximumSize(new java.awt.Dimension(1500, 900));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ITERA");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(110, 60, 78, 34);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PERPUSTAKAAN");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(70, 40, 146, 26);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\#RIGBY MULTIMEDIA\\Desktop\\New folder\\logoitera.png")); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(70, 550, 100, 117);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/foto/icons8_library_96px.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 30, 100, 80);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("Update Buku");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6);
        jLabel6.setBounds(60, 240, 150, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/foto/icons8_books_26px.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 230, 30, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/foto/icons8_search_26px.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 280, 30, 30);

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 0));
        jLabel13.setText("Lihat Data Buku");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel13);
        jLabel13.setBounds(60, 280, 150, 30);

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 102, 0));
        jLabel14.setText("Lihat Data Peminjam");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel14);
        jLabel14.setBounds(60, 320, 160, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/foto/icons8_reading_30px.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 320, 30, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/foto/icons8_group_30px.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 360, 30, 30);

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 102, 0));
        jLabel16.setText("Lihat Data Anggota");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel16);
        jLabel16.setBounds(60, 360, 150, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/foto/icons8_logout_rounded_left_26px.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel15);
        jLabel15.setBounds(20, 500, 30, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 0));
        jLabel12.setText("Log Out");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel12);
        jLabel12.setBounds(70, 500, 140, 30);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_exit1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_exit1MouseClicked

    private void jButton_minimize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_minimize1MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton_minimize1MouseClicked

    private void jButton_minimize1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_minimize1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_minimize1ActionPerformed

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseDragged
        int x =evt.getXOnScreen();
        int y =evt.getYOnScreen();
      

        this.setLocation(x-mouseX, y-mouseY);
        System.out.println(x+","+y);
    }//GEN-LAST:event_jPanel5MouseDragged

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        int mouseX = evt.getX();
        int mouseY = evt.getY();
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x =evt.getXOnScreen();
        int y =evt.getYOnScreen();
   

        this.setLocation(x-mouseX, y-mouseY);
        System.out.println(x+","+y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        int mouseX = evt.getX();
        int mouseY = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jTextField_searchbookFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_searchbookFocusGained
        // TODO add your handling code here:
        if(jTextField_searchbook.getText().trim().toLowerCase().equals("search book")){
            jTextField_searchbook.setText("");
            jTextField_searchbook.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_searchbookFocusGained

    private void jTextField_searchbookFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_searchbookFocusLost
        // TODO add your handling code here:
        if(jTextField_searchbook.getText().trim().equals("") || jTextField_searchbook.getText().trim().toLowerCase().equals("search book")){
            jTextField_searchbook.setText("search book");
            jTextField_searchbook.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField_searchbookFocusLost

    private void jTextField_searchbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_searchbookActionPerformed
 String cari = jTextField_searchbook.getText();  
        try {
            com.mysql.jdbc.Statement stat = (com.mysql.jdbc.Statement) Db_Koneksi.getKoneksi().createStatement();
 ResultSet res =stat.executeQuery("Select * From databuku Where id_buku LIKE '%"+cari+"%'"+"OR judul_buku LIKE '%"+cari+"%'"+" OR penerbit LIKE '%"+cari+"%'"+ "OR pengarang LIKE '%"+cari+"%'"+" OR stok LIKE '%"+cari+"%'");
            if (res.next()) {
                jTextField_idbuku.setText(res.getString("id_buku"));
                jTextField_judul.setText(res.getString("judul_buku"));
                jTextField_penerbit.setText(res.getString("penerbit"));
                jTextField_pengarang.setText(res.getString("pengarang"));
                 jTextField_stok.setText(res.getString("stok"));
            } else {
               jTextField_idbuku.setText("");
                jTextField_judul.setText("");
                jTextField_penerbit.setText("");
                jTextField_pengarang.setText("");
                 jTextField_stok.setText("");
                  JOptionPane.showMessageDialog(rootPane, "Data yang dicari tidak ada !!!!");
            }
        } catch(SQLException err){
             JOptionPane.showMessageDialog(rootPane, "Data yang dicari tidak ada !!!!");

        }    




    }//GEN-LAST:event_jTextField_searchbookActionPerformed

    private void jTextField_idbukuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_idbukuFocusGained
        // TODO add your handling code here:
        if(jTextField_idbuku.getText().trim().toLowerCase().equals("id buku")){
            jTextField_idbuku.setText("");
            jTextField_idbuku.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_idbukuFocusGained

    private void jTextField_idbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idbukuActionPerformed
      
       
    }//GEN-LAST:event_jTextField_idbukuActionPerformed

    private void jTextField_idbukuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_idbukuKeyTyped
        // TODO add your handling code here:
       /* if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }*/
    }//GEN-LAST:event_jTextField_idbukuKeyTyped
 
    private void jTextField_judulFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_judulFocusGained
        // TODO add your handling code here:
        if(jTextField_judul.getText().trim().toLowerCase().equals("judul")){
            jTextField_judul.setText("");
            jTextField_judul.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_judulFocusGained

    private void jTextField_judulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_judulActionPerformed
      
    }//GEN-LAST:event_jTextField_judulActionPerformed

    private void jTextField_pengarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_pengarangFocusGained
        // TODO add your handling code here:
        if(jTextField_pengarang.getText().trim().toLowerCase().equals("pengarang")){
            jTextField_pengarang.setText("");
            jTextField_pengarang.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_pengarangFocusGained

    private void jTextField_pengarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_pengarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_pengarangActionPerformed

    private void jTextField_penerbitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_penerbitFocusGained
        // TODO add your handling code here:
        if(jTextField_penerbit.getText().trim().toLowerCase().equals("penerbit")){
            jTextField_penerbit.setText("");
            jTextField_penerbit.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_penerbitFocusGained

    private void jTextField_penerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_penerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_penerbitActionPerformed

    private void jTextField_stokFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_stokFocusGained
        // TODO add your handling code here:
        if(jTextField_stok.getText().trim().toLowerCase().equals("stok")){
            jTextField_stok.setText("");
            jTextField_stok.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_stokFocusGained

    private void jTextField_stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_stokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_stokActionPerformed

    private void jButton_exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_exit1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet ss;

        Update_Buku form = new Update_Buku();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet ss;

        Update_Buku form = new Update_Buku();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet ss;

        cari_buku form = new cari_buku();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet ss;

        cari_buku form = new cari_buku();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet ss;

        DataPeminjam form = new DataPeminjam();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet ss;

        DataPeminjam form = new DataPeminjam();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet ss;

        DataAnggota form = new DataAnggota();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet ss;

        DataAnggota form = new DataAnggota();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet ss;

        login form = new login();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet ss;

        login form = new login();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
 
  
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextField_searchbookKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchbookKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_searchbookKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            String cari = jTextField_searchbook.getText();  
        try {
            com.mysql.jdbc.Statement stat = (com.mysql.jdbc.Statement) Db_Koneksi.getKoneksi().createStatement();
 ResultSet res =stat.executeQuery("Select * From databuku Where id_buku LIKE '%"+cari+"%'"+"OR judul_buku LIKE '%"+cari+"%'"+" OR penerbit LIKE '%"+cari+"%'"+ "OR pengarang LIKE '%"+cari+"%'"+" OR stok LIKE '%"+cari+"%'");
            if (res.next()) {
                jTextField_idbuku.setText(res.getString("id_buku"));
                jTextField_judul.setText(res.getString("judul_buku"));
                jTextField_penerbit.setText(res.getString("penerbit"));
                jTextField_pengarang.setText(res.getString("pengarang"));
                 jTextField_stok.setText(res.getString("stok"));
            } else {
               jTextField_idbuku.setText("");
                jTextField_judul.setText("");
                jTextField_penerbit.setText("");
                jTextField_pengarang.setText("");
                 jTextField_stok.setText("");
            }
        } catch(SQLException err){
             JOptionPane.showMessageDialog(rootPane, "Data yang dicari tidak ada !!!!");

        }
        // TODO add your handling code here:
        /*  try {
            String sql = "SELECT `id_buku`, `judul_buku`, `penerbit`, `pengarang`, `stok` FROM `data_buku` WHERE  judul_buku = '"+jTextField_searchbook.getText()+"' ";

            PreparedStatement pst;
            pst = LoginToRegister.getConnection().PreparedStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            pst.setString(1, jTextField_searchbook.getText());
            if(rs.next()){
                String add1=rs.getString("id_buku");
                jTextField_idbuku.setText(add1);
                String add2=rs.getString("judul_buku");
                jTextField_judul.setText(add1);
                String add3=rs.getString("pengarang");
                jTextField_pengarang.setText(add3);
                String add4=rs.getString("penerbit");
                jTextField_penerbit.setText(add4);
                String add5=rs.getString("stok");
                jTextField_stok.setText(add5);
            }
        } catch (SQLException e) {
            Logger.getLogger(search_buku.class.getName()).log(Level.SEVERE, null, e);
            //JOptionPane.showMessageDialog(null, e);
            */
            /*try{
                ResultSet rs = LoginToRegister.getData("SELECT * FROM `data_buku` WHERE `judul_buku` = " +jTextField_searchbook.getText()+"");

                if(rs.first()){
                    jTextField_searchbook.setText(rs.getString("judul_buku"));
                    jTextField_searchbook.setText(rs.getString("id_buku"));
                    jTextField_searchbook.setText(rs.getString("penerbit"));
                    jTextField_searchbook.setText(rs.getString("pengarang"));
                    jTextField_searchbook.setText(rs.getString("stok"));
                }
            } catch (Exception e){
                e.printStackTrace();
            }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField_idbukuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_idbukuKeyReleased
       
    }//GEN-LAST:event_jTextField_idbukuKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cari_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cari_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cari_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cari_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cari_buku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_exit1;
    private javax.swing.JButton jButton_minimize1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_idbuku;
    private javax.swing.JLabel jLabel_judul;
    private javax.swing.JLabel jLabel_penerbit;
    private javax.swing.JLabel jLabel_pengarang;
    private javax.swing.JLabel jLabel_stok;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_idbuku;
    private javax.swing.JTextField jTextField_judul;
    private javax.swing.JTextField jTextField_penerbit;
    private javax.swing.JTextField jTextField_pengarang;
    private javax.swing.JTextField jTextField_searchbook;
    private javax.swing.JTextField jTextField_stok;
    // End of variables declaration//GEN-END:variables
}
