/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;
 
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author NURANISDA
 */
public class Update_Buku extends javax.swing.JFrame {

    /**
     * Creates new form Update_Buku
     */
    public Update_Buku() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextField_idbuku = new javax.swing.JTextField();
        jLabel_idbuku = new javax.swing.JLabel();
        jLabel_judulbuku = new javax.swing.JLabel();
        jTextField_judulbuku = new javax.swing.JTextField();
        jTextField_pengarang = new javax.swing.JTextField();
        jLabel_pengarang = new javax.swing.JLabel();
        jLabel_penerbit = new javax.swing.JLabel();
        jTextField_penerbit = new javax.swing.JTextField();
        jTextField_stok = new javax.swing.JTextField();
        jLabel_stok = new javax.swing.JLabel();
        jButton_tambah = new javax.swing.JButton();
        jLabel_menu = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton_exit1 = new javax.swing.JButton();
        jButton_minimize1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1313, 696));
        getContentPane().setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField_idbuku.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_idbuku.setText("id buku");
        jTextField_idbuku.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_idbukuFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_idbukuFocusLost(evt);
            }
        });
        jTextField_idbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idbukuActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_idbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 320, 40));

        jLabel_idbuku.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabel_idbuku.setText("Id Buku:");
        jPanel1.add(jLabel_idbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        jLabel_judulbuku.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabel_judulbuku.setText("Judul Buku:");
        jPanel1.add(jLabel_judulbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        jTextField_judulbuku.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_judulbuku.setText("judul buku");
        jTextField_judulbuku.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_judulbukuFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_judulbukuFocusLost(evt);
            }
        });
        jTextField_judulbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_judulbukuActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_judulbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 320, 40));

        jTextField_pengarang.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_pengarang.setText("pengarang");
        jTextField_pengarang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_pengarangFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_pengarangFocusLost(evt);
            }
        });
        jTextField_pengarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_pengarangActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_pengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 320, 40));

        jLabel_pengarang.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabel_pengarang.setText("Pengarang:");
        jPanel1.add(jLabel_pengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        jLabel_penerbit.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabel_penerbit.setText("Penerbit:");
        jPanel1.add(jLabel_penerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        jTextField_penerbit.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_penerbit.setText("penerbit");
        jTextField_penerbit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_penerbitFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_penerbitFocusLost(evt);
            }
        });
        jTextField_penerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_penerbitActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_penerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 320, 40));

        jTextField_stok.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_stok.setText("stok");
        jTextField_stok.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_stokFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_stokFocusLost(evt);
            }
        });
        jTextField_stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_stokActionPerformed(evt);
            }
        });
        jTextField_stok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_stokKeyTyped(evt);
            }
        });
        jPanel1.add(jTextField_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 320, 40));

        jLabel_stok.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabel_stok.setText("Stok:");
        jPanel1.add(jLabel_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        jButton_tambah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_tambah.setText("Tambah Data Buku");
        jButton_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_tambahActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));

        jLabel_menu.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel_menu.setText(">> Kembali ke Menu");
        jLabel_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_menuMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, -1));

        jLabel19.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        jLabel19.setText("Menambah Data Buku");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 930, 470));

        jPanel6.setBackground(new java.awt.Color(153, 102, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/foto/icons8_administrator_52px_1.png"))); // NOI18N
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 60));

        jLabel18.setBackground(new java.awt.Color(139, 71, 38));
        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Hello, Admin!");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 160, 35));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 930, 140));

        jButton_exit1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_exit1.setForeground(new java.awt.Color(255, 0, 0));
        jButton_exit1.setText("x");
        jButton_exit1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_exit1MouseClicked(evt);
            }
        });
        jButton_exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exit1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton_exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, 30, -1));

        jButton_minimize1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_minimize1.setForeground(new java.awt.Color(255, 0, 0));
        jButton_minimize1.setText("-");
        jButton_minimize1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_minimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_minimize1MouseClicked(evt);
            }
        });
        jButton_minimize1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_minimize1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton_minimize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 30, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/foto/large3.jpg"))); // NOI18N
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 700));

        getContentPane().add(jPanel5);
        jPanel5.setBounds(229, 0, 1090, 700);

        jPanel2.setBackground(new java.awt.Color(255, 215, 0));
        jPanel2.setMaximumSize(new java.awt.Dimension(1500, 900));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ITERA");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(110, 60, 78, 34);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PERPUSTAKAAN");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(70, 40, 146, 26);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\#RIGBY MULTIMEDIA\\Desktop\\New folder\\logoitera.png")); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(70, 550, 100, 117);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/foto/icons8_library_96px.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 30, 100, 80);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("Update Buku");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6);
        jLabel6.setBounds(60, 240, 150, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/foto/icons8_books_26px.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 230, 30, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/foto/icons8_search_26px.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 280, 30, 30);

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 0));
        jLabel13.setText("Lihat Data Buku");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel13);
        jLabel13.setBounds(60, 280, 150, 30);

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 102, 0));
        jLabel14.setText("Lihat Data Peminjam");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel14);
        jLabel14.setBounds(60, 320, 160, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/foto/icons8_reading_30px.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 320, 30, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/foto/icons8_group_30px.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 360, 30, 30);

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 102, 0));
        jLabel16.setText("Lihat Data Anggota");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel16);
        jLabel16.setBounds(60, 360, 150, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/foto/icons8_logout_rounded_left_26px.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel15);
        jLabel15.setBounds(20, 500, 30, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 0));
        jLabel12.setText("Log Out");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel12);
        jLabel12.setBounds(70, 500, 140, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 230, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_exit1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_exit1MouseClicked

    private void jButton_exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_exit1ActionPerformed

    private void jButton_minimize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_minimize1MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton_minimize1MouseClicked

    private void jButton_minimize1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_minimize1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_minimize1ActionPerformed

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseDragged
        int x =evt.getXOnScreen();
        int y =evt.getYOnScreen();
        int mouseX = 0;
        int mouseY = 0;

        this.setLocation(x-mouseX, y-mouseY);
        System.out.println(x+","+y);
    }//GEN-LAST:event_jPanel5MouseDragged

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        int mouseX = evt.getX();
        int mouseY = evt.getY();
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x =evt.getXOnScreen();
        int y =evt.getYOnScreen();
        int mouseX = 0;
        int mouseY = 0;

        this.setLocation(x-mouseX, y-mouseY);
        System.out.println(x+","+y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        int mouseX = evt.getX();
        int mouseY = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jTextField_idbukuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_idbukuFocusGained
        // TODO add your handling code here:
        if(jTextField_idbuku.getText().trim().toLowerCase().equals("id buku")){
            jTextField_idbuku.setText("");
            jTextField_idbuku.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_idbukuFocusGained

    private void jTextField_idbukuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_idbukuFocusLost
        // TODO add your handling code here:
        if(jTextField_idbuku.getText().trim().equals("") || jTextField_idbuku.getText().trim().toLowerCase().equals("id buku")){
            jTextField_idbuku.setText("id buku");
            jTextField_idbuku.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField_idbukuFocusLost

    private void jTextField_idbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idbukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idbukuActionPerformed

    private void jTextField_judulbukuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_judulbukuFocusGained
        // TODO add your handling code here:
        if(jTextField_judulbuku.getText().trim().toLowerCase().equals("judul buku")){
            jTextField_judulbuku.setText("");
            jTextField_judulbuku.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_judulbukuFocusGained

    private void jTextField_judulbukuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_judulbukuFocusLost
        // TODO add your handling code here:
        if(jTextField_judulbuku.getText().trim().equals("") || jTextField_judulbuku.getText().trim().toLowerCase().equals("judul buku")){
            jTextField_judulbuku.setText("judul buku");
            jTextField_judulbuku.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField_judulbukuFocusLost

    private void jTextField_judulbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_judulbukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_judulbukuActionPerformed

    private void jTextField_pengarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_pengarangFocusGained
        // TODO add your handling code here:
        if(jTextField_pengarang.getText().trim().toLowerCase().equals("pengarang")){
            jTextField_pengarang.setText("");
            jTextField_pengarang.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_pengarangFocusGained

    private void jTextField_pengarangFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_pengarangFocusLost
        // TODO add your handling code here:
        if(jTextField_pengarang.getText().trim().equals("") || jTextField_pengarang.getText().trim().toLowerCase().equals("pengarang")){
            jTextField_pengarang.setText("pengarang hp");
            jTextField_pengarang.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField_pengarangFocusLost

    private void jTextField_pengarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_pengarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_pengarangActionPerformed

    private void jTextField_penerbitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_penerbitFocusGained
        // TODO add your handling code here:
        if(jTextField_penerbit.getText().trim().toLowerCase().equals("penerbit")){
            jTextField_penerbit.setText("");
            jTextField_penerbit.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_penerbitFocusGained

    private void jTextField_penerbitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_penerbitFocusLost
        // TODO add your handling code here:
        if(jTextField_penerbit.getText().trim().equals("") || jTextField_penerbit.getText().trim().toLowerCase().equals("penerbit")){
            jTextField_penerbit.setText("penerbit");
            jTextField_penerbit.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField_penerbitFocusLost

    private void jTextField_penerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_penerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_penerbitActionPerformed

    private void jTextField_stokFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_stokFocusGained
        // TODO add your handling code here:
        if(jTextField_stok.getText().trim().toLowerCase().equals("stok")){
            jTextField_stok.setText("");
            jTextField_stok.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_stokFocusGained

    private void jTextField_stokFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_stokFocusLost
        // TODO add your handling code here:
        if(jTextField_stok.getText().trim().equals("") || jTextField_stok.getText().trim().toLowerCase().equals("stok")){
            jTextField_stok.setText("stok");
            jTextField_stok.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField_stokFocusLost

    private void jTextField_stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_stokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_stokActionPerformed

    private void jTextField_stokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_stokKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_stokKeyTyped

    public boolean cekIdBuku(String id_buku){
        PreparedStatement st;
        ResultSet rs;
        boolean username_exist = false;
        
        String query = "SELECT * FROM `data_buku` WHERE `id_buku` = ?";
        
        try{
            st = LoginToRegister.getConnection().prepareStatement(query);
            st.setString(1, id_buku);
            rs = st.executeQuery();
            
            if(rs.next()){
                username_exist = true;
                JOptionPane.showMessageDialog(null, "Id Buku ini telah tersedia, silahkan masukkan id lain!", "ID gagal", 2);
            }
        } catch (SQLException ex){
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return username_exist;
    }
    
    private void jButton_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_tambahActionPerformed
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet rs;

        String judul_buku = jTextField_judulbuku.getText();
        String stok = jTextField_stok.getText();
        String id_buku = jTextField_idbuku.getText();
        String penerbit = jTextField_penerbit.getText();
        String pengarang = jTextField_pengarang.getText();
        
        if(TambahBuku()){
            if(!cekIdBuku(id_buku)){
                PreparedStatement ps;
                //ResultSet rs;

                String registerUserQuery = "INSERT INTO `databuku`(`id_buku`,`judul_buku`,`penerbit`,`pengarang`,`stok`) VALUES (?,?,?,?,?)";

                try {
                    ps = LoginToRegister.getConnection().prepareStatement(registerUserQuery);
                    ps.setString(1, id_buku);
                    ps.setString(2, judul_buku);
                    ps.setString(3, pengarang);
                    ps.setString(4, penerbit);
                    ps.setString(5, stok);

                    if(ps.executeUpdate() != 0){
                        JOptionPane.showMessageDialog(null, "Penambahan Data Buku Berhasilt!");
                    }else{
                        JOptionPane.showMessageDialog(null, "Error: Harap cek kembali");
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_jButton_tambahActionPerformed

    private void jLabel_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_menuMouseClicked
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet ss;

        Menu1 form = new Menu1();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel_menuMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet ss;

        Update_Buku form = new Update_Buku();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet ss;

        Update_Buku form = new Update_Buku();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet ss;

        cari_buku form = new cari_buku();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet ss;

        cari_buku form = new cari_buku();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet ss;

        DataPeminjam form = new DataPeminjam();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet ss;

        DataPeminjam form = new DataPeminjam();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet ss;

        DataAnggota form = new DataAnggota();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet ss;

        DataAnggota form = new DataAnggota();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet ss;

        login form = new login();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet ss;

        login form = new login();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    public boolean TambahBuku(){
        String id_buku = jTextField_idbuku.getText();
        String judul_buku = jTextField_judulbuku.getText();
        String pengarang = jTextField_pengarang.getText();
        String penerbit = jTextField_penerbit.getText();
        String stok = jTextField_stok.getText();
        
        if(id_buku.trim().equals("") || judul_buku.trim().equals("") || pengarang.trim().equals("") || penerbit.trim().equals("") || stok.trim().equals("") ){
            JOptionPane.showMessageDialog(null, "Isi semua data!", "Data Kosong!", 2);
            return false;
        }else{
            return true;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Update_Buku().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_exit1;
    private javax.swing.JButton jButton_minimize1;
    private javax.swing.JButton jButton_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_idbuku;
    private javax.swing.JLabel jLabel_judulbuku;
    private javax.swing.JLabel jLabel_menu;
    private javax.swing.JLabel jLabel_penerbit;
    private javax.swing.JLabel jLabel_pengarang;
    private javax.swing.JLabel jLabel_stok;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField_idbuku;
    private javax.swing.JTextField jTextField_judulbuku;
    private javax.swing.JTextField jTextField_penerbit;
    private javax.swing.JTextField jTextField_pengarang;
    private javax.swing.JTextField jTextField_stok;
    // End of variables declaration//GEN-END:variables
}
